name: Build and test Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2.2.0
        with:
          go-version: 1.17

      - name: Build
        run: |
          source .envrc
          go build ./...

      - name: Test
        run: | 
          source .envrc
          go test -v ./...
