// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: loggregator-api/v2/envelope.proto

package loggregator_v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Log_Type int32

const (
	Log_OUT Log_Type = 0
	Log_ERR Log_Type = 1
)

// Enum value maps for Log_Type.
var (
	Log_Type_name = map[int32]string{
		0: "OUT",
		1: "ERR",
	}
	Log_Type_value = map[string]int32{
		"OUT": 0,
		"ERR": 1,
	}
)

func (x Log_Type) Enum() *Log_Type {
	p := new(Log_Type)
	*p = x
	return p
}

func (x Log_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Log_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_loggregator_api_v2_envelope_proto_enumTypes[0].Descriptor()
}

func (Log_Type) Type() protoreflect.EnumType {
	return &file_loggregator_api_v2_envelope_proto_enumTypes[0]
}

func (x Log_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Log_Type.Descriptor instead.
func (Log_Type) EnumDescriptor() ([]byte, []int) {
	return file_loggregator_api_v2_envelope_proto_rawDescGZIP(), []int{3, 0}
}

type Envelope struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timestamp      int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SourceId       string                 `protobuf:"bytes,2,opt,name=source_id,proto3" json:"source_id,omitempty"`
	InstanceId     string                 `protobuf:"bytes,8,opt,name=instance_id,proto3" json:"instance_id,omitempty"`
	DeprecatedTags map[string]*Value      `protobuf:"bytes,3,rep,name=deprecated_tags,proto3" json:"deprecated_tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags           map[string]string      `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Message:
	//
	//	*Envelope_Log
	//	*Envelope_Counter
	//	*Envelope_Gauge
	//	*Envelope_Timer
	//	*Envelope_Event
	Message       isEnvelope_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_loggregator_api_v2_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_loggregator_api_v2_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_loggregator_api_v2_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Envelope) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Envelope) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Envelope) GetDeprecatedTags() map[string]*Value {
	if x != nil {
		return x.DeprecatedTags
	}
	return nil
}

func (x *Envelope) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Envelope) GetMessage() isEnvelope_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Envelope) GetLog() *Log {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *Envelope) GetCounter() *Counter {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Counter); ok {
			return x.Counter
		}
	}
	return nil
}

func (x *Envelope) GetGauge() *Gauge {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Gauge); ok {
			return x.Gauge
		}
	}
	return nil
}

func (x *Envelope) GetTimer() *Timer {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Timer); ok {
			return x.Timer
		}
	}
	return nil
}

func (x *Envelope) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isEnvelope_Message interface {
	isEnvelope_Message()
}

type Envelope_Log struct {
	Log *Log `protobuf:"bytes,4,opt,name=log,proto3,oneof"`
}

type Envelope_Counter struct {
	Counter *Counter `protobuf:"bytes,5,opt,name=counter,proto3,oneof"`
}

type Envelope_Gauge struct {
	Gauge *Gauge `protobuf:"bytes,6,opt,name=gauge,proto3,oneof"`
}

type Envelope_Timer struct {
	Timer *Timer `protobuf:"bytes,7,opt,name=timer,proto3,oneof"`
}

type Envelope_Event struct {
	Event *Event `protobuf:"bytes,10,opt,name=event,proto3,oneof"`
}

func (*Envelope_Log) isEnvelope_Message() {}

func (*Envelope_Counter) isEnvelope_Message() {}

func (*Envelope_Gauge) isEnvelope_Message() {}

func (*Envelope_Timer) isEnvelope_Message() {}

func (*Envelope_Event) isEnvelope_Message() {}

type EnvelopeBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batch         []*Envelope            `protobuf:"bytes,1,rep,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvelopeBatch) Reset() {
	*x = EnvelopeBatch{}
	mi := &file_loggregator_api_v2_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvelopeBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvelopeBatch) ProtoMessage() {}

func (x *EnvelopeBatch) ProtoReflect() protoreflect.Message {
	mi := &file_loggregator_api_v2_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvelopeBatch.ProtoReflect.Descriptor instead.
func (*EnvelopeBatch) Descriptor() ([]byte, []int) {
	return file_loggregator_api_v2_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *EnvelopeBatch) GetBatch() []*Envelope {
	if x != nil {
		return x.Batch
	}
	return nil
}

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*Value_Text
	//	*Value_Integer
	//	*Value_Decimal
	Data          isValue_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_loggregator_api_v2_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_loggregator_api_v2_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_loggregator_api_v2_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *Value) GetData() isValue_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Value) GetText() string {
	if x != nil {
		if x, ok := x.Data.(*Value_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *Value) GetInteger() int64 {
	if x != nil {
		if x, ok := x.Data.(*Value_Integer); ok {
			return x.Integer
		}
	}
	return 0
}

func (x *Value) GetDecimal() float64 {
	if x != nil {
		if x, ok := x.Data.(*Value_Decimal); ok {
			return x.Decimal
		}
	}
	return 0
}

type isValue_Data interface {
	isValue_Data()
}

type Value_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type Value_Integer struct {
	Integer int64 `protobuf:"varint,2,opt,name=integer,proto3,oneof"`
}

type Value_Decimal struct {
	Decimal float64 `protobuf:"fixed64,3,opt,name=decimal,proto3,oneof"`
}

func (*Value_Text) isValue_Data() {}

func (*Value_Integer) isValue_Data() {}

func (*Value_Decimal) isValue_Data() {}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Type          Log_Type               `protobuf:"varint,2,opt,name=type,proto3,enum=loggregator.v2.Log_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_loggregator_api_v2_envelope_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_loggregator_api_v2_envelope_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_loggregator_api_v2_envelope_proto_rawDescGZIP(), []int{3}
}

func (x *Log) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Log) GetType() Log_Type {
	if x != nil {
		return x.Type
	}
	return Log_OUT
}

type Counter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Delta         uint64                 `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	Total         uint64                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Counter) Reset() {
	*x = Counter{}
	mi := &file_loggregator_api_v2_envelope_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Counter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Counter) ProtoMessage() {}

func (x *Counter) ProtoReflect() protoreflect.Message {
	mi := &file_loggregator_api_v2_envelope_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Counter.ProtoReflect.Descriptor instead.
func (*Counter) Descriptor() ([]byte, []int) {
	return file_loggregator_api_v2_envelope_proto_rawDescGZIP(), []int{4}
}

func (x *Counter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Counter) GetDelta() uint64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *Counter) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Gauge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       map[string]*GaugeValue `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gauge) Reset() {
	*x = Gauge{}
	mi := &file_loggregator_api_v2_envelope_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gauge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gauge) ProtoMessage() {}

func (x *Gauge) ProtoReflect() protoreflect.Message {
	mi := &file_loggregator_api_v2_envelope_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gauge.ProtoReflect.Descriptor instead.
func (*Gauge) Descriptor() ([]byte, []int) {
	return file_loggregator_api_v2_envelope_proto_rawDescGZIP(), []int{5}
}

func (x *Gauge) GetMetrics() map[string]*GaugeValue {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type GaugeValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unit          string                 `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GaugeValue) Reset() {
	*x = GaugeValue{}
	mi := &file_loggregator_api_v2_envelope_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GaugeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GaugeValue) ProtoMessage() {}

func (x *GaugeValue) ProtoReflect() protoreflect.Message {
	mi := &file_loggregator_api_v2_envelope_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GaugeValue.ProtoReflect.Descriptor instead.
func (*GaugeValue) Descriptor() ([]byte, []int) {
	return file_loggregator_api_v2_envelope_proto_rawDescGZIP(), []int{6}
}

func (x *GaugeValue) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *GaugeValue) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Timer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Start         int64                  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Stop          int64                  `protobuf:"varint,3,opt,name=stop,proto3" json:"stop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timer) Reset() {
	*x = Timer{}
	mi := &file_loggregator_api_v2_envelope_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timer) ProtoMessage() {}

func (x *Timer) ProtoReflect() protoreflect.Message {
	mi := &file_loggregator_api_v2_envelope_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timer.ProtoReflect.Descriptor instead.
func (*Timer) Descriptor() ([]byte, []int) {
	return file_loggregator_api_v2_envelope_proto_rawDescGZIP(), []int{7}
}

func (x *Timer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Timer) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Timer) GetStop() int64 {
	if x != nil {
		return x.Stop
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_loggregator_api_v2_envelope_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_loggregator_api_v2_envelope_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_loggregator_api_v2_envelope_proto_rawDescGZIP(), []int{8}
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_loggregator_api_v2_envelope_proto protoreflect.FileDescriptor

const file_loggregator_api_v2_envelope_proto_rawDesc = "" +
	"\n" +
	"!loggregator-api/v2/envelope.proto\x12\x0eloggregator.v2\"\x81\x05\n" +
	"\bEnvelope\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tsource_id\x18\x02 \x01(\tR\tsource_id\x12 \n" +
	"\vinstance_id\x18\b \x01(\tR\vinstance_id\x12V\n" +
	"\x0fdeprecated_tags\x18\x03 \x03(\v2,.loggregator.v2.Envelope.DeprecatedTagsEntryR\x0fdeprecated_tags\x126\n" +
	"\x04tags\x18\t \x03(\v2\".loggregator.v2.Envelope.TagsEntryR\x04tags\x12'\n" +
	"\x03log\x18\x04 \x01(\v2\x13.loggregator.v2.LogH\x00R\x03log\x123\n" +
	"\acounter\x18\x05 \x01(\v2\x17.loggregator.v2.CounterH\x00R\acounter\x12-\n" +
	"\x05gauge\x18\x06 \x01(\v2\x15.loggregator.v2.GaugeH\x00R\x05gauge\x12-\n" +
	"\x05timer\x18\a \x01(\v2\x15.loggregator.v2.TimerH\x00R\x05timer\x12-\n" +
	"\x05event\x18\n" +
	" \x01(\v2\x15.loggregator.v2.EventH\x00R\x05event\x1aX\n" +
	"\x13DeprecatedTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.loggregator.v2.ValueR\x05value:\x028\x01\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\amessage\"?\n" +
	"\rEnvelopeBatch\x12.\n" +
	"\x05batch\x18\x01 \x03(\v2\x18.loggregator.v2.EnvelopeR\x05batch\"]\n" +
	"\x05Value\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12\x1a\n" +
	"\ainteger\x18\x02 \x01(\x03H\x00R\ainteger\x12\x1a\n" +
	"\adecimal\x18\x03 \x01(\x01H\x00R\adecimalB\x06\n" +
	"\x04data\"g\n" +
	"\x03Log\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.loggregator.v2.Log.TypeR\x04type\"\x18\n" +
	"\x04Type\x12\a\n" +
	"\x03OUT\x10\x00\x12\a\n" +
	"\x03ERR\x10\x01\"I\n" +
	"\aCounter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x04R\x05delta\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x04R\x05total\"\x9d\x01\n" +
	"\x05Gauge\x12<\n" +
	"\ametrics\x18\x01 \x03(\v2\".loggregator.v2.Gauge.MetricsEntryR\ametrics\x1aV\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.loggregator.v2.GaugeValueR\x05value:\x028\x01\"6\n" +
	"\n" +
	"GaugeValue\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"E\n" +
	"\x05Timer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x03R\x05start\x12\x12\n" +
	"\x04stop\x18\x03 \x01(\x03R\x04stop\"1\n" +
	"\x05Event\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04bodyBs\n" +
	"\x1forg.cloudfoundry.loggregator.v2B\x13LoggregatorEnvelopeZ;code.cloudfoundry.org/go-loggregator/v10/rpc/loggregator_v2b\x06proto3"

var (
	file_loggregator_api_v2_envelope_proto_rawDescOnce sync.Once
	file_loggregator_api_v2_envelope_proto_rawDescData []byte
)

func file_loggregator_api_v2_envelope_proto_rawDescGZIP() []byte {
	file_loggregator_api_v2_envelope_proto_rawDescOnce.Do(func() {
		file_loggregator_api_v2_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loggregator_api_v2_envelope_proto_rawDesc), len(file_loggregator_api_v2_envelope_proto_rawDesc)))
	})
	return file_loggregator_api_v2_envelope_proto_rawDescData
}

var file_loggregator_api_v2_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_loggregator_api_v2_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_loggregator_api_v2_envelope_proto_goTypes = []any{
	(Log_Type)(0),         // 0: loggregator.v2.Log.Type
	(*Envelope)(nil),      // 1: loggregator.v2.Envelope
	(*EnvelopeBatch)(nil), // 2: loggregator.v2.EnvelopeBatch
	(*Value)(nil),         // 3: loggregator.v2.Value
	(*Log)(nil),           // 4: loggregator.v2.Log
	(*Counter)(nil),       // 5: loggregator.v2.Counter
	(*Gauge)(nil),         // 6: loggregator.v2.Gauge
	(*GaugeValue)(nil),    // 7: loggregator.v2.GaugeValue
	(*Timer)(nil),         // 8: loggregator.v2.Timer
	(*Event)(nil),         // 9: loggregator.v2.Event
	nil,                   // 10: loggregator.v2.Envelope.DeprecatedTagsEntry
	nil,                   // 11: loggregator.v2.Envelope.TagsEntry
	nil,                   // 12: loggregator.v2.Gauge.MetricsEntry
}
var file_loggregator_api_v2_envelope_proto_depIdxs = []int32{
	10, // 0: loggregator.v2.Envelope.deprecated_tags:type_name -> loggregator.v2.Envelope.DeprecatedTagsEntry
	11, // 1: loggregator.v2.Envelope.tags:type_name -> loggregator.v2.Envelope.TagsEntry
	4,  // 2: loggregator.v2.Envelope.log:type_name -> loggregator.v2.Log
	5,  // 3: loggregator.v2.Envelope.counter:type_name -> loggregator.v2.Counter
	6,  // 4: loggregator.v2.Envelope.gauge:type_name -> loggregator.v2.Gauge
	8,  // 5: loggregator.v2.Envelope.timer:type_name -> loggregator.v2.Timer
	9,  // 6: loggregator.v2.Envelope.event:type_name -> loggregator.v2.Event
	1,  // 7: loggregator.v2.EnvelopeBatch.batch:type_name -> loggregator.v2.Envelope
	0,  // 8: loggregator.v2.Log.type:type_name -> loggregator.v2.Log.Type
	12, // 9: loggregator.v2.Gauge.metrics:type_name -> loggregator.v2.Gauge.MetricsEntry
	3,  // 10: loggregator.v2.Envelope.DeprecatedTagsEntry.value:type_name -> loggregator.v2.Value
	7,  // 11: loggregator.v2.Gauge.MetricsEntry.value:type_name -> loggregator.v2.GaugeValue
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_loggregator_api_v2_envelope_proto_init() }
func file_loggregator_api_v2_envelope_proto_init() {
	if File_loggregator_api_v2_envelope_proto != nil {
		return
	}
	file_loggregator_api_v2_envelope_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Log)(nil),
		(*Envelope_Counter)(nil),
		(*Envelope_Gauge)(nil),
		(*Envelope_Timer)(nil),
		(*Envelope_Event)(nil),
	}
	file_loggregator_api_v2_envelope_proto_msgTypes[2].OneofWrappers = []any{
		(*Value_Text)(nil),
		(*Value_Integer)(nil),
		(*Value_Decimal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loggregator_api_v2_envelope_proto_rawDesc), len(file_loggregator_api_v2_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_loggregator_api_v2_envelope_proto_goTypes,
		DependencyIndexes: file_loggregator_api_v2_envelope_proto_depIdxs,
		EnumInfos:         file_loggregator_api_v2_envelope_proto_enumTypes,
		MessageInfos:      file_loggregator_api_v2_envelope_proto_msgTypes,
	}.Build()
	File_loggregator_api_v2_envelope_proto = out.File
	file_loggregator_api_v2_envelope_proto_goTypes = nil
	file_loggregator_api_v2_envelope_proto_depIdxs = nil
}
