// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: loggregator-api/v2/ingress.proto

package loggregator_v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngressResponse) Reset() {
	*x = IngressResponse{}
	mi := &file_loggregator_api_v2_ingress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngressResponse) ProtoMessage() {}

func (x *IngressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loggregator_api_v2_ingress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngressResponse.ProtoReflect.Descriptor instead.
func (*IngressResponse) Descriptor() ([]byte, []int) {
	return file_loggregator_api_v2_ingress_proto_rawDescGZIP(), []int{0}
}

type BatchSenderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSenderResponse) Reset() {
	*x = BatchSenderResponse{}
	mi := &file_loggregator_api_v2_ingress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSenderResponse) ProtoMessage() {}

func (x *BatchSenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loggregator_api_v2_ingress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSenderResponse.ProtoReflect.Descriptor instead.
func (*BatchSenderResponse) Descriptor() ([]byte, []int) {
	return file_loggregator_api_v2_ingress_proto_rawDescGZIP(), []int{1}
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_loggregator_api_v2_ingress_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loggregator_api_v2_ingress_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_loggregator_api_v2_ingress_proto_rawDescGZIP(), []int{2}
}

var File_loggregator_api_v2_ingress_proto protoreflect.FileDescriptor

const file_loggregator_api_v2_ingress_proto_rawDesc = "" +
	"\n" +
	" loggregator-api/v2/ingress.proto\x12\x0eloggregator.v2\x1a!loggregator-api/v2/envelope.proto\"\x11\n" +
	"\x0fIngressResponse\"\x15\n" +
	"\x13BatchSenderResponse\"\x0e\n" +
	"\fSendResponse2\xf0\x01\n" +
	"\aIngress\x12G\n" +
	"\x06Sender\x12\x18.loggregator.v2.Envelope\x1a\x1f.loggregator.v2.IngressResponse\"\x00(\x01\x12U\n" +
	"\vBatchSender\x12\x1d.loggregator.v2.EnvelopeBatch\x1a#.loggregator.v2.BatchSenderResponse\"\x00(\x01\x12E\n" +
	"\x04Send\x12\x1d.loggregator.v2.EnvelopeBatch\x1a\x1c.loggregator.v2.SendResponse\"\x00Br\n" +
	"\x1forg.cloudfoundry.loggregator.v2B\x12LoggregatorIngressZ;code.cloudfoundry.org/go-loggregator/v10/rpc/loggregator_v2b\x06proto3"

var (
	file_loggregator_api_v2_ingress_proto_rawDescOnce sync.Once
	file_loggregator_api_v2_ingress_proto_rawDescData []byte
)

func file_loggregator_api_v2_ingress_proto_rawDescGZIP() []byte {
	file_loggregator_api_v2_ingress_proto_rawDescOnce.Do(func() {
		file_loggregator_api_v2_ingress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loggregator_api_v2_ingress_proto_rawDesc), len(file_loggregator_api_v2_ingress_proto_rawDesc)))
	})
	return file_loggregator_api_v2_ingress_proto_rawDescData
}

var file_loggregator_api_v2_ingress_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_loggregator_api_v2_ingress_proto_goTypes = []any{
	(*IngressResponse)(nil),     // 0: loggregator.v2.IngressResponse
	(*BatchSenderResponse)(nil), // 1: loggregator.v2.BatchSenderResponse
	(*SendResponse)(nil),        // 2: loggregator.v2.SendResponse
	(*Envelope)(nil),            // 3: loggregator.v2.Envelope
	(*EnvelopeBatch)(nil),       // 4: loggregator.v2.EnvelopeBatch
}
var file_loggregator_api_v2_ingress_proto_depIdxs = []int32{
	3, // 0: loggregator.v2.Ingress.Sender:input_type -> loggregator.v2.Envelope
	4, // 1: loggregator.v2.Ingress.BatchSender:input_type -> loggregator.v2.EnvelopeBatch
	4, // 2: loggregator.v2.Ingress.Send:input_type -> loggregator.v2.EnvelopeBatch
	0, // 3: loggregator.v2.Ingress.Sender:output_type -> loggregator.v2.IngressResponse
	1, // 4: loggregator.v2.Ingress.BatchSender:output_type -> loggregator.v2.BatchSenderResponse
	2, // 5: loggregator.v2.Ingress.Send:output_type -> loggregator.v2.SendResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_loggregator_api_v2_ingress_proto_init() }
func file_loggregator_api_v2_ingress_proto_init() {
	if File_loggregator_api_v2_ingress_proto != nil {
		return
	}
	file_loggregator_api_v2_envelope_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loggregator_api_v2_ingress_proto_rawDesc), len(file_loggregator_api_v2_ingress_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loggregator_api_v2_ingress_proto_goTypes,
		DependencyIndexes: file_loggregator_api_v2_ingress_proto_depIdxs,
		MessageInfos:      file_loggregator_api_v2_ingress_proto_msgTypes,
	}.Build()
	File_loggregator_api_v2_ingress_proto = out.File
	file_loggregator_api_v2_ingress_proto_goTypes = nil
	file_loggregator_api_v2_ingress_proto_depIdxs = nil
}
