// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: loggregator-api/v2/ingress.proto

package loggregator_v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ingress_Sender_FullMethodName      = "/loggregator.v2.Ingress/Sender"
	Ingress_BatchSender_FullMethodName = "/loggregator.v2.Ingress/BatchSender"
	Ingress_Send_FullMethodName        = "/loggregator.v2.Ingress/Send"
)

// IngressClient is the client API for Ingress service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IngressClient interface {
	Sender(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Envelope, IngressResponse], error)
	BatchSender(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EnvelopeBatch, BatchSenderResponse], error)
	Send(ctx context.Context, in *EnvelopeBatch, opts ...grpc.CallOption) (*SendResponse, error)
}

type ingressClient struct {
	cc grpc.ClientConnInterface
}

func NewIngressClient(cc grpc.ClientConnInterface) IngressClient {
	return &ingressClient{cc}
}

func (c *ingressClient) Sender(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Envelope, IngressResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Ingress_ServiceDesc.Streams[0], Ingress_Sender_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Envelope, IngressResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ingress_SenderClient = grpc.ClientStreamingClient[Envelope, IngressResponse]

func (c *ingressClient) BatchSender(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EnvelopeBatch, BatchSenderResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Ingress_ServiceDesc.Streams[1], Ingress_BatchSender_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EnvelopeBatch, BatchSenderResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ingress_BatchSenderClient = grpc.ClientStreamingClient[EnvelopeBatch, BatchSenderResponse]

func (c *ingressClient) Send(ctx context.Context, in *EnvelopeBatch, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, Ingress_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IngressServer is the server API for Ingress service.
// All implementations must embed UnimplementedIngressServer
// for forward compatibility.
type IngressServer interface {
	Sender(grpc.ClientStreamingServer[Envelope, IngressResponse]) error
	BatchSender(grpc.ClientStreamingServer[EnvelopeBatch, BatchSenderResponse]) error
	Send(context.Context, *EnvelopeBatch) (*SendResponse, error)
	mustEmbedUnimplementedIngressServer()
}

// UnimplementedIngressServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngressServer struct{}

func (UnimplementedIngressServer) Sender(grpc.ClientStreamingServer[Envelope, IngressResponse]) error {
	return status.Error(codes.Unimplemented, "method Sender not implemented")
}
func (UnimplementedIngressServer) BatchSender(grpc.ClientStreamingServer[EnvelopeBatch, BatchSenderResponse]) error {
	return status.Error(codes.Unimplemented, "method BatchSender not implemented")
}
func (UnimplementedIngressServer) Send(context.Context, *EnvelopeBatch) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedIngressServer) mustEmbedUnimplementedIngressServer() {}
func (UnimplementedIngressServer) testEmbeddedByValue()                 {}

// UnsafeIngressServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngressServer will
// result in compilation errors.
type UnsafeIngressServer interface {
	mustEmbedUnimplementedIngressServer()
}

func RegisterIngressServer(s grpc.ServiceRegistrar, srv IngressServer) {
	// If the following call panics, it indicates UnimplementedIngressServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ingress_ServiceDesc, srv)
}

func _Ingress_Sender_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngressServer).Sender(&grpc.GenericServerStream[Envelope, IngressResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ingress_SenderServer = grpc.ClientStreamingServer[Envelope, IngressResponse]

func _Ingress_BatchSender_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngressServer).BatchSender(&grpc.GenericServerStream[EnvelopeBatch, BatchSenderResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ingress_BatchSenderServer = grpc.ClientStreamingServer[EnvelopeBatch, BatchSenderResponse]

func _Ingress_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnvelopeBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngressServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ingress_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngressServer).Send(ctx, req.(*EnvelopeBatch))
	}
	return interceptor(ctx, in, info, handler)
}

// Ingress_ServiceDesc is the grpc.ServiceDesc for Ingress service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ingress_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loggregator.v2.Ingress",
	HandlerType: (*IngressServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Ingress_Send_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sender",
			Handler:       _Ingress_Sender_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BatchSender",
			Handler:       _Ingress_BatchSender_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "loggregator-api/v2/ingress.proto",
}
